[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.0",
    "discord-py>=2.6.3",
    "google-genai>=1.41.0",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
